#ifndef UR_CONTROL_GUI_URCONTROLGUIDEFINES_H_
#define UR_CONTROL_GUI_URCONTROLGUIDEFINES_H_

enum class DashboardCommand {
  POWER_ON_ROBOT,
  POWER_OFF_ROBOT,
  BRAKE_RELEASE,
  GET_ROBOT_MODE,
  GET_ROBOT_SAFETY_MODE
};

#endif /* UR_CONTROL_GUI_URCONTROLGUIDEFINES_H_ */
