name: Docker Image CI

on:
  push:
    branches: [ "master", "foxy", "ci_cd" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: ./scripts/assisted_install/full_install_in_docker.sh